error if images not found

diff --git a/app/scripts/create_deployment b/app/scripts/create_deployment
--- a/app/scripts/create_deployment
+++ b/app/scripts/create_deployment
@@ -4,6 +4,7 @@ set -e
 
 DEFAULT_LATEST_AMI="false"
 latest_ami="$DEFAULT_LATEST_AMI"
+success="true"
 
 EXECDIR="$(pwd)"
 SOURCE=${BASH_SOURCE[0]} # resolve the script dir even if a symlink is used to this script
@@ -52,6 +53,7 @@ function warn_if_invalid {
   local -r var_name=$3
 
   if [[ -z "$ami_result" || "$ami_result" == "null" ]]; then
+    success="false"
     log_warn "Images required for deployment are not present.  You will need to build them before continuing."
     log_warn "$var_name"
     log_warn ""
@@ -119,6 +121,11 @@ warn_if_invalid "$ami_role" "$TF_VAR_provisioner_ami_id" "TF_VAR_provisioner_ami
 ami_role="firehawk_amazonlinux2_nicedcv_ami"
 export TF_VAR_workstation_amazonlinux2_nicedcv_ami_id=$(retrieve_ami $latest_ami $ami_role $TF_VAR_ami_commit_hash)
 warn_if_invalid "$ami_role" "$TF_VAR_workstation_amazonlinux2_nicedcv_ami_id" "TF_VAR_workstation_amazonlinux2_nicedcv_ami_id"
+
+if [[ "$success" == "false" ]]; then
+  echo "ERROR: Cannot depoloy without all images."
+  exit 1
+fi
 
 cd $SCRIPTDIR/../modules
 rm -fr codedeploy-app-firehawk.zip
